---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/users/login":
    post:
      summary: User Login
      tags:
      - Login
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - title
          - content
      responses:
        '201':
          description: User Login
        '422':
          description: invalid request
  "/api/users/slots":
    get:
      summary: Slots
      tags:
      - Slots
      consumes:
      - application/json
      security:
      - Bearer: {}
      responses:
        '200':
          description: Slots
        '422':
          description: invalid request
securityDefinitions:
  Bearer:
    description: Authorization
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
