---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: User Login
      tags:
      - Login
      parameters: []
      responses:
        '201':
          description: User Login
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - title
              - content
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
